# Service name
service: erc20-bridge-serverless

# Serverless framework version
frameworkVersion: "=1.37.1"

# Provider
provider:
  name: aws
  runtime: python3.7

  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1

  # Additional statements of the Lambda's IAM Role
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-erc20BridgeInfo"

  # Function common environment variables
  environment:
    STAGE: ${self:provider.stage}

    # Public chain
    PUBLIC_CHAIN_RPC_URL: ${file(./config/${self:provider.stage}.yml):PUBLIC_CHAIN_RPC_URL}
    PUBLIC_CHAIN_BRIDGE_CONTRACT_ADDRESS: ${file(./config/${self:provider.stage}.yml):PUBLIC_CHAIN_BRIDGE_CONTRACT_ADDRESS}
    # Private chain
    PRIVATE_CHAIN_RPC_URL: ${file(./config/${self:provider.stage}.yml):PRIVATE_CHAIN_RPC_URL}
    PRIVATE_CHAIN_BRIDGE_CONTRACT_ADDRESS: ${file(./config/${self:provider.stage}.yml):PRIVATE_CHAIN_BRIDGE_CONTRACT_ADDRESS}

  # VPC
  vpc:
    subnetIds:
      - ${file(./config/${self:provider.stage}.yml):VPC_SUBNET_IDS}
    securityGroupIds:
      - ${file(./config/${self:provider.stage}.yml):VPC_SECURITY_GROUP_IDS}

  # Package
  package:
    include:
      - src/operator.py


# Lambda functions
functions:
  bridgePublicToPrivate:
    handler: handler.bridge_public_to_private

    # Scheduling
    events:
      - schedule: rate(10 minutes)

    # Function specific environts
    environment:
      PRIVATE_CHAIN_OPERATOR_PRIVATE_KEY: ${file(./config/${self:provider.stage}.yml):PRIVATE_CHAIN_OPERATOR_PRIVATE_KEY}
      PRIVATE_CHAIN_OPERATOR_SIGNER: ${file(./config/${self:provider.stage}.yml):PRIVATE_CHAIN_OPERATOR_SIGNER}
      PRIVATE_CHAIN_GAS: ${file(./config/${self:provider.stage}.yml):PRIVATE_CHAIN_GAS}
      PRIVATE_CHAIN_GAS_PRICE: ${file(./config/${self:provider.stage}.yml):PRIVATE_CHAIN_GAS_PRICE}

  brigePrivateToPublic:
    handler: handler.bridge_private_to_public

    # Scheduling
    events:
      - schedule: rate(10 minutes)

    # Function specific environts
    environment:
      PUBLIC_CHAIN_GAS: ${file(./config/${self:provider.stage}.yml):PUBLIC_CHAIN_GAS}
      PUBLIC_CHAIN_GAS_PRICE: ${file(./config/${self:provider.stage}.yml):PUBLIC_CHAIN_GAS_PRICE}
      PUBLIC_CHAIN_OPERATOR_PRIVATE_KEY: ${file(./config/${self:provider.stage}.yml):PUBLIC_CHAIN_OPERATOR_PRIVATE_KEY}
      PUBLIC_CHAIN_OPERATOR_SIGNER: ${file(./config/${self:provider.stage}.yml):PUBLIC_CHAIN_OPERATOR_SIGNER}

  applyRelayPrivate:
    handler: handler.apply_relay_private

    # Function specific environts
    environment:
      PRIVATE_CHAIN_OPERATOR_PRIVATE_KEY: ${file(./config/${self:provider.stage}.yml):PRIVATE_CHAIN_OPERATOR_PRIVATE_KEY}
      PRIVATE_CHAIN_OPERATOR_SIGNER: ${file(./config/${self:provider.stage}.yml):PRIVATE_CHAIN_OPERATOR_SIGNER}
      PRIVATE_CHAIN_GAS: ${file(./config/${self:provider.stage}.yml):PRIVATE_CHAIN_GAS}
      PRIVATE_CHAIN_GAS_PRICE: ${file(./config/${self:provider.stage}.yml):PRIVATE_CHAIN_GAS_PRICE}

  applyRelayPublic:
    handler: handler.apply_relay_public

    # Function specific environts
    environment:
      PUBLIC_CHAIN_GAS: ${file(./config/${self:provider.stage}.yml):PUBLIC_CHAIN_GAS}
      PUBLIC_CHAIN_GAS_PRICE: ${file(./config/${self:provider.stage}.yml):PUBLIC_CHAIN_GAS_PRICE}
      PUBLIC_CHAIN_OPERATOR_PRIVATE_KEY: ${file(./config/${self:provider.stage}.yml):PUBLIC_CHAIN_OPERATOR_PRIVATE_KEY}
      PUBLIC_CHAIN_OPERATOR_SIGNER: ${file(./config/${self:provider.stage}.yml):PUBLIC_CHAIN_OPERATOR_SIGNER}


# Plugins
plugins:
  - serverless-python-requirements
  - serverless-dynamodb-local


# Resources
resources:
  Resources:
    # DynamoDB
    erc20BridgeInfo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-erc20BridgeInfo
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


# Custom settings
custom:
  pythonRequirements:
    dockerizePip: true
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: false
